### ISSUE TITLE
TopBar左侧返回图标不能使用

### ISSUE THREAD

**Issue by 1004634740** [tuya/tuya-panel-kit#100]
## 组件

组件名称
TopBar
## 版本

- 组件版本：4.0.0
- react 版本：16.8.3
- react-native 版本：0.59.10

## 概述

Bug 问题概述
异形屏手机不能加载左边返回图标。目前 荣耀v30已经复现

## Bug 行为

Bug 的表现行为
左侧返回图标被档
## 期望行为

组件的正确行为
左边返回图标能正确显示
## 期望发布日期

期望 bug 解决后发布的正式版本号或日期

## 附件
![3b835eff-8d70-466e-a1cb-b0417fe0866f(3)](https://user-images.githubusercontent.com/54577520/128007558-50bbb7ad-710d-4b2f-b1b2-5a738b7dc76f.jpg)

附上图片或日志

**Comment by ZengBeauty** [comment]
这边不建议隐藏状态栏
![wecom-temp-a92866b7805b22b06ea879a23bf19d28](https://user-images.githubusercontent.com/34674396/128164383-00087d37-8d9c-47e7-81ad-e51da9363464.jpg)
