### ISSUE TITLE
BrickButton组件样式丢失

### ISSUE THREAD

**Issue by andyyxw** [tuya/tuya-panel-kit#135]
## 组件

BrickButton

## 版本

- 组件版本：4.7.7
- react 版本：16.8.3
- react-native 版本：0.59.10

## 概述

`theme`与`wrapperStyle`/`textStyle`等style属性一起使用时，`theme`中的一些样式会丢失

## Bug 行为

`theme`中的一些样式会丢失

## 期望行为

能正确合并传入的所有样式

## 期望发布日期

-

## 附件

单独使用`theme`正确显示：
![wecom-temp-1286611a3ed8859e2bb2d7bb79d943b0](https://user-images.githubusercontent.com/41931722/132511768-f663fe1c-5e83-476d-9e2a-fc248fa27b27.png)
<img width="263" alt="wecom-temp-dce7df5d8975bd333b7ff85645f7522e" src="https://user-images.githubusercontent.com/41931722/132511796-626d5056-642c-4cd5-a61f-a55848244c22.png">
额外传入了`wrapperStyle`/`textStyle`后，`theme`中的样式丢失：
![wecom-temp-415815cddbc20bfacf0c053313a52f47](https://user-images.githubusercontent.com/41931722/132511872-fea0b305-aafc-49ce-826c-4af6fc6dd762.png)
<img width="269" alt="wecom-temp-838221ff0ccfe0420c1aa505e61da381" src="https://user-images.githubusercontent.com/41931722/132511983-429e86e4-c17d-48e8-b1e7-94c43f1e31e8.png">

**Comment by ZengBeauty** [comment]
可通过指传递 style 相关属性或者 只传递 theme 来实现业务逻辑
