### ISSUE TITLE
TYMobile.verSupported is not a function. (In 'TYMobile.verSupported('2.91')', 'TYMobile.verSupported' is undefined)

### ISSUE THREAD

**Issue by SANSTONE** [tuya/tuya-panel-kit#137]
## 组件

组件名称

## 版本

- 组件版本：
- react 版本：
- react-native 版本：

## 概述

Bug 问题概述

## 重现步骤

1. aaa
2. bbb
3. ccc

## Bug 行为

Bug 的表现行为

## 期望行为

组件的正确行为

## 期望发布日期

期望 bug 解决后发布的正式版本号或日期

## 附件

附上图片或日志

**Comment by ZengBeauty** [comment]
您好，暂未复现这个问题，请问 App 的 rnVersion 是什么版本？ @SANSTONE

**Comment by ShinyLeee** [comment]
duplicated
