### ISSUE TITLE
TYMobile.verSupported is not a function. (In 'TYMobile.verSupported('2.91')', 'TYMobile.verSupported' is undefined)

### ISSUE THREAD

**Issue by SANSTONE** [tuya/tuya-panel-kit#138]
## 组件

组件名称

## 版本

- 组件版本："tuya-panel-kit": "~4.7.6"
- react 版本： "react": "16.8.3"
- react-native 版本："react-native": "0.59.10"

## 概述

Bug 问题概述
TYMobile.verSupported is not a function. (In 'TYMobile.verSupported('2.91')', 'TYMobile.verSupported' is undefined)
## 重现步骤

1. 初始化demo中 “airPurifier” 工程

## Bug 行为

Bug 的表现行为

## 期望行为

组件的正确行为

## 期望发布日期

期望 bug 解决后发布的正式版本号或日期

## 附件

附上图片或日志
![Simulator Screen Shot - iPhone 11 - 2021-09-13 at 10 53 17](https://user-images.githubusercontent.com/15245310/133016951-9f596f66-ebb1-42e7-9b71-4fad8f2cacd7.png)

**Comment by ZengBeauty** [comment]
您好，暂未复现这个问题，请问 App 的 rnVersion 是什么版本？
