### ISSUE TITLE
打包后线上闪退

### ISSUE THREAD

**Issue by xt0112** [tuya/tuya-panel-kit#150]
## 组件

组件名称

## 版本

- 组件版本：
- react 版本：16.8.3
- react-native 版本： 0.59

## 概述

Bug 问题概述
打包成功后 上传os 平台后 查看线上直接闪退。
    "tuya-panel-kit": "^4.6.6" 加上尖括号会失败， 去掉尖括号打包 且版本为4.6.6 成功

## Bug 行为

Bug 的表现行为
打包成功后 上传os 平台后 查看线上直接闪退。
    "tuya-panel-kit": "^4.6.6" 加上尖括号会失败， 去掉尖括号打包 且版本为4.6.6 成功

## 期望行为
打包成功后上传os 平台后查看线上不会闪退

组件的正确行为

## 期望发布日期

期望 bug 解决后发布的正式版本号或日期

## 附件

附上图片或日志

**Comment by ShinyLeee** [comment]
@xt0112 项目 package.json 付下，[demo](https://github.com/tuya/tuya-panel-demo) 项目里的应该不会吧

**Comment by xt0112** [comment]
[package.txt](https://github.com/tuya/tuya-panel-kit/files/7509653/package.txt)
demo 项目打包上线有尖括号也失败
运行项目时 能下载相关的包，但是运行也会直接报错
