### ISSUE TITLE
设备没有离线， 离线弹窗出现

### ISSUE THREAD

**Issue by xt0112** [tuya/tuya-panel-kit#153]
## 组件
组件名称  蓝牙离线弹窗
## 版本
- 组件版本：
- react 版本：16.8.3
- react-native 版本：0.59

## 概述
Bug 问题概述
设备没有离线，面板首页直接锁频，或者按home键退出，过大约半小时再进入面板，会先弹出离线弹窗，维持1，2秒的样子自动消失。然后正常显示。

## 重现步骤
 设备没有离线的情况下，首页直接锁屏，或者按home键退出，过大约半小时再进入面板，会先弹出离线弹窗，维持1，2秒的样子自动消失。然后正常显示

## Bug 行为
Bug 的表现行为

## 期望行为
设备没有离线的情况下，首页直接锁频，或者按home键退出，过大约半小时再进入面板，不会先弹出离线弹窗。

组件的正确行为

## 期望发布日期
期望 bug 解决后发布的正式版本号或日期
尽快

## 附件
附上图片或日志
![36f34784-b77c-46ff-82a6-8155c02e8312](https://user-images.githubusercontent.com/92367731/137857232-61e4b7e6-ea55-4406-a59f-aeb386e4cb79.jpg)
图片上我打印了离线状态改变的值 目前看没有改变。
![image](https://user-images.githubusercontent.com/92367731/137857320-908b35bc-b45d-4e64-8d30-c184aace3547.png)
纯UI 界面 无任何逻辑。 仅显示两个text 
![bedcdbbf-9fb5-4e53-ba26-23d762c66f23](https://user-images.githubusercontent.com/92367731/137872014-26020d44-f2fc-48b7-ad6d-6c6d9349d31a.jpg)
![462c7536-cc46-4f16-8e18-32634a54ef88](https://user-images.githubusercontent.com/92367731/137872147-a25fd6b2-cb91-4c6c-8e44-5878455907e3.jpg)
目前看纯UI 发现，没有走 case 'deviceOnline'  ，而是走的default。附图如上

新增代码如下：
![image](https://user-images.githubusercontent.com/92367731/137872270-d94306f8-e4ff-4576-afeb-20a311b10674.png)

**Comment by ShinyLeee** [comment]
安卓机后台切换推送网络断开在链接通知导致，close
