### ISSUE TITLE
Regarding Panel SDK

### ISSUE THREAD

**Issue by ghalibt** [tuya/tuya-panel-kit#164]
We want to know that is the Panel SDK  can draw the map of WBR3 Vaccum cleaner, is there any example to fetch the data we are sending map data to the Tuya cloud from WBR3 vaccum cleaner but we need to fetch for from Tuya cloud and to draw it on the app. However, we currently do not know the steps please guide us in this matter.

**Comment by ShinyLeee** [comment]
We add LaserSweepRobot demo in [v0.1.13](https://github.com/tuya/tuya-panel-demo/releases/tag/v0.1.13)
