### ISSUE TITLE
Notification 组件设置  enableClose = false & autoCloseTime 之后单行文案不居中

### ISSUE THREAD

**Issue by wenyAlab** [tuya/tuya-panel-kit#173]
**组件**: Notification

**问题描述**：ios 设置 Notification enableClose 属性改为false, 并且设置  autoCloseTime 属性之后, 文案和icon没有垂直居中

[相似问题](https://github.com/tuya/tuya-panel-kit/issues/63)

### 1: 问题截图/视频：
![wecom-temp-844926347f115f6b3913c14958e9e92a](https://user-images.githubusercontent.com/27913987/147200006-a4f288ca-cbf1-42d3-8f8d-0b6eead98f24.jpg)

### 2: 版本：

组件版本：4.7.11
react 版本：16.8.3
react-native 版本：0.59.10

### 3: 复现机型：
iPhone XR

### 4: 问题代码片段/分支：

`
    Notification.show({
        variant: 'warning',
        message: Strings.getLang('device_offline'),
        onClose: () => {
          Notification.hide();
        },
        enableClose: false,
        autoCloseTime: 2000,
        theme: {
          successIcon: 'red',
          errorIcon: 'yellow',
          warningIcon: 'red',
        },
    });
`

### 5. 期望: 

设置 Notification enableClose 属性改为false, 并且设置  autoCloseTime 属性之后, 文案和icon 能够垂直居中

**Comment by ZengBeauty** [comment]
4.8.4 版本已经修复
