### ISSUE TITLE
Dialog.confirm(） 在onCancle 里面执行返回上一页会导致蒙版没消失

### ISSUE THREAD

**Issue by AsuraZhu** [tuya/tuya-panel-kit#178]
## 组件

组件名称

## 版本

- 组件版本：
- react 版本：
- react-native 版本：

## 概述

Bug 问题概述
Dialog.confirm({
      title: '',
      subTitle: '退出当前页面，本次称重数据将不会保存',
      cancelText: '回首页',
      confirmText: '继续称重',
      onCancel: () => {
        navigation.pop();
      },
      // onCancel: ()=>{
      //   // close();
      //   // navigation.pop();
      // },
      onConfirm: (_, { close }) => {
        close();
      },
    });
    点击回首页，会导致弹框的蒙层 没有消失，
    
    看了下源码：onCancel放在this.setState({show:false},()=>{onCancel()}) 里面就行了，this.setState是异步事件，navigation.pop();返回页面会比  this.setState({ show: false });快
 _handleCancel = () => {
      const { onCancel } = this.props;
      this.setState({ show: false });
      this.actionFn = () => typeof onCancel === 'function' && onCancel();
    };

## 重现步骤

1. aaa
2. bbb
3. ccc

## Bug 行为

Bug 的表现行为

## 期望行为

组件的正确行为

## 期望发布日期

期望 bug 解决后发布的正式版本号或日期

## 附件

附上图片或日志

**Comment by ZengBeauty** [comment]
目前业务项目中可以通过异步处理 onCancel 来解决问题，同时我们也会在下一个组件库版本解决该问题 @AsuraZhu
