### ISSUE TITLE
Regarding Lz4 decompression library for ios

### ISSUE THREAD

**Issue by ghalibt** [tuya/tuya-panel-kit#183]
We want to know any source code references of the Lz4 decompression library used in TUYA App for decompressing the map data. We got the map data but don't know regarding the LZ4 decompression library which is used by TUYA in their app.  Thanks for your help.

**Comment by ShinyLeee** [comment]
I think you can Create a ticket, we only can deal with component issue here.
![image](https://user-images.githubusercontent.com/13724426/155253826-58c7aac8-1ac7-4b80-9aa9-db1a8611d3f2.png)
