### ISSUE TITLE
开源代码交流

### ISSUE THREAD

**Issue by 1uokun** [tuya/tuya-panel-kit#184]
你好，我是https://github.com/ant-design/ant-design-mobile-rn 的协作者，我想和你们交流一下相关组件的实现

我优化了一下`Carousel`代码，主要是`loop`(我们称`infinite`)循环滑动的优化:
https://github.com/ant-design/ant-design-mobile-rn/pull/1215 
这样的问题我们都存在，有需要也可以帮助优化

然后我在优化`Tabs`的时候发现你们已经做了非常棒的优化，所以想对Tabs系列组件进一步交流一下：[链接](https://github.com/tuya/tuya-panel-kit/tree/main/packages/tuya-panel-kit/src/components/tabs)

**Comment by ShinyLeee** [comment]
`Carousel`  我们内部使用不多，因此未针对优化处理， `Tabs` 组件是通过纯手势实现的，做了一些 Tab 容器的预加载，下划线动效之类的。

**Comment by 1uokun** [comment]
之前有过面板开发体验，好像只能在TYSDK环境内使用

那我这边参考你们的思路去优化啦😊

**Comment by ShinyLeee** [comment]
https://github.com/tuya/tuya-panel-kit/tree/main/packages/tuya-panel-tabs

这个包相对来说还是较纯净一些
