### ISSUE TITLE
Tab 组件如何隐藏底部TabBar

### ISSUE THREAD

**Issue by XiaooSe** [tuya/tuya-panel-kit#189]
## 组件

组件名称: Tab

## 版本

- 组件版本：^4.7.5
- react 版本：16.8.3
- react-native 版本：0.59

## 概述

Bug 问题概述

## 重现步骤

1. Tab 按钮如何隐藏底部TabBar

## Bug 行为

业务场景使用Tab, 会出现只有一个tab页的场景，想隐藏

tabsContainerStyle = _props2.tabsContainerStyle,
tabStyle = _props2.tabStyle,
tabBarStyle = _props2.tabBarStyle,

此三属性均无效

## 期望行为

可以主动隐藏底部TabBar

**Comment by ZengBeauty** [comment]
设置 tabStyle: { display: none }
