### ISSUE TITLE
RotationView组件loading动画阻塞InteractionManager任务队列

### ISSUE THREAD

**Issue by yuanlllshuai** [tuya/tuya-panel-kit#20]
## 组件

rotation-view

## 组件版本

4.0.0

## 概述

组件中的loading循环实现为递归调用，当动画开启后，即使组件销毁掉，仍会在其他页面中阻塞InteractionManager任务队列

## 重现步骤

1. 将loading设置为true后，退出页面销毁组件
2. 进入使用await InteractionManager.runAfterInteractions()的页面，InteractionManager下的代码被阻塞不执行

## Bug 行为

阻塞InteractionManager任务队列

## 期望行为

组件销毁后，不阻塞InteractionManager任务队列

## 期望发布日期

2021年1月8日

## 建议解决方法

Animated.timing增加isInteraction字段参数可设置为false

**Comment by ZengBeauty** [comment]
类型申明已添加： https://github.com/tuya/DefinitelyTyped/commit/b9089bd16bde8390db87c1bbfd5e7525b46d3d05
