### ISSUE TITLE
安装完成之后，引入使用时报错 TYMobile.getMobileInfo is unfefined

### ISSUE THREAD

**Issue by hu-qi** [tuya/tuya-panel-kit#23]
# 引入使用时报错

![65E071FB837CAF3931721EA139325F1F](https://user-images.githubusercontent.com/17986122/103434729-53a6f280-4c40-11eb-893d-3a28a75c1dce.jpg)

# 环境

```
$ node -v
v12.1.0

$ uname -a
MINGW64_NT-10.0-19042 huqi 3.0.7-338.x86_64 2019-07-03 15:16 UTC x86_64 Msys

 "tuya-panel-kit": "^4.1.0"
 "tuya-panel-kit": "^4.1.0"
```

**Comment by youngjuning** [comment]
1. 提供一下 react-native、react 的版本
2. 提供脱敏的复现项目

**Comment by youngjuning** [comment]
@hu-qi 看上去 RN 的版本并不支持 ts，RN 是从 0.57 开始支持 ts。组件库最佳的适配版本是 0.59

**Comment by zhaomengqiao** [comment]
@youngjuning 您好，rn0.63可以用吗？好像0.63和tuya的设备控制库最新版本有冲突

**Comment by youngjuning** [comment]
原生那边不支持的，要使用RN0.59.10 youngjuning 邮箱：youngjuning@aliyun.com 签名由 网易邮箱大师 定制 在2021年02月07日 19:01，MengQiaoZhao 写道： @youngjuning 您好，rn0.63可以用吗？好像0.63和tuya的设备控制库最新版本有冲突 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
