### ISSUE TITLE
Modal onlyLastModalVisible属性不生效

### ISSUE THREAD

**Issue by huangtiti** [tuya/tuya-panel-kit#24]
使用example
popup里的【列表选择弹出层(单选)】，只弹出了第二个弹框【单选2】
点击取消关闭弹窗后无法再次点击任何东西
![测试1](https://user-images.githubusercontent.com/42531359/103737664-90eaf600-502d-11eb-9592-622c6db780c9.png)
现象：
https://user-images.githubusercontent.com/42531359/103738930-c7297500-502f-11eb-968d-d49a4c5fc9c6.mov

**Comment by youngjuning** [comment]
٩( 'ω' )و get！we will fix it soon.
