### ISSUE TITLE
Progress 组件扩展支持性

### ISSUE THREAD

**Issue by 1004634740** [tuya/tuya-panel-kit#32]
## 组件

组件名称
Progress

## 版本

- 组件版本：2.0.0-rc.7
- react 版本：16.0.0
- react-native 版本：0.51.0

## 概述

Bug 问题概述
我把组件复制出来，然后把小于360°时候出现的起始点和终点注释之后会出现以下情况（小屏手机，目前出现这个情况的手机如图二）

## Bug 行为

Bug 的表现行为
起始的圆角只有一半
## 期望行为

组件的正确行为
起始的圆角应该都存在
## 期望发布日期

期望 bug 解决后发布的正式版本号或日期

## 附件

附上图片或日志
图一
![image](https://user-images.githubusercontent.com/54577520/105825033-11cc5a80-5ffa-11eb-94fa-62264d85e881.png)
图二
![image](https://user-images.githubusercontent.com/54577520/105825290-640d7b80-5ffa-11eb-9f83-1a9df144ee2b.png)

**Comment by ZengBeauty** [comment]
按照提供的描述，起点和终点都不会存在圆球的。
如果代码是复制出来自行修改的话，还需您自己做兼容处理的。
