### ISSUE TITLE
slider组件在部分机型不适配

### ISSUE THREAD

**Issue by JILL1231** [tuya/tuya-panel-kit#39]
## 组件

Slider 滑动选择器

## 版本

- 组件版本：3.4.8
- react 版本："16.0.0",
- react-native 版本："5.1"

## 概述

renderThumb 超出 track 的部分在魅族和华为20等机型显示不全

## 重现步骤

调用代码：
`<Slider
            style={styles.slider}
            value={value}
            maximumValue={maximumValue}  // 最大值
            minimumValue={minimumValue}  // 最小值
            trackStyle={styles.trackStyle} // 轨道样式
            thumbStyle={[styles.thumbStyle, { borderRadius: value }]} // 滑块样式 { borderRadius: num }无实效，只为了能够更新renderThumb
            stepValue={1}
            canTouchTrack={true}
            reverseValue={true}
            animateTransitions={true}
            horizontal={false}
            maximumTrackTintColor="transparent"
            minimumTrackTintColor="#A0D2FF"
            renderThumb={() => this.renderThumb(value)}
            renderMaximumTrack={this.renderTrack}
            onSlidingComplete={onSlidingComplete}
          />`

thumb代码：
`renderThumb = (value: number) => {
    const val = value ? value / 10 : 0;
    return (
      <View style={styles.thumb}>
        <TYText style={styles.unit}>{parseInt('' + val)}</TYText>
        <TYText>cm</TYText>
        <Image
          source={res.whiteBall}
          resizeMode="contain"
        />
      </View>
    )
  }`

## Bug 行为

魅族和华为20等机型显示不全，苹果手机目前都可以，部分安卓也可以

## 期望行为

适配安卓急性

## 期望发布日期

2021-02-06

## 附件
魅族和华为20等机型显示如下
<img width="133" alt="q1" src="https://user-images.githubusercontent.com/11407881/106688421-0a640d00-6609-11eb-98c0-5f14d8447576.png">

其他机型显示如下：
<img width="137" alt="q2" src="https://user-images.githubusercontent.com/11407881/106688461-21a2fa80-6609-11eb-83b9-e918f22a259c.png">

 @@

**Comment by ZengBeauty** [comment]
经过验证，是组件使用不当造成的。
该项目在小米手机，魅族手机都是存在上述问题的。主要原因是项目代码中Slider 组件的 style 没有给足够的宽度，自定义的 thumb 也没有给宽度，是导致安卓手机被截掉的主要原因，解决这个原因安卓手机会正常展示。
同样的，由于项目中过多使用绝对定位布局，还需自行调试解决兼容性问题。
