### ISSUE TITLE
Dialog 多次弹出问题

### ISSUE THREAD

**Issue by holize** [tuya/tuya-panel-kit#40]
## 组件
Dialog  Modal
组件名称
Dialog  Modal
## 版本
当前
- 组件版本：
- react 版本：16.8.3
- react-native 版本：0.59.10

## 概述

在modal 组件中触发弹出一个Dialog.confirm，当按下确认时，关掉Dialog并使用异步关掉 Modal，
页面中Dialog被关掉后，会再次弹出

## Bug 行为
多次弹出 Dialog.confirm
## 期望行为

仅弹出一次Dialog.confirm

## 期望发布日期

尽快

## 附件

附上图片或日志

**Comment by ShinyLeee** [comment]
#51 和这个问题一起看
