### ISSUE TITLE
Progress 组件使用存在问题

### ISSUE THREAD

**Issue by 1247918007** [tuya/tuya-panel-kit#42]
## 组件

Progress

## 版本

- 组件版本：~2.0.0-rc.3
- react 版本：16.0.0
- react-native 版本：0.51.0

## 概述

Progress 未按照预期效果显示

## 重现步骤

<Progress
            style={{ marginTop: 30 }}
            scaleHeight={15}
            startDegree={270}
            andDegree={360}
            min={0}
            max={100}
            value={25}
            thumbRadius={7}
            needMaxCircle={true}
            needMinCircle={true}
            foreColor="#135381"
            stepValue={5}
            startColor="#6a00d4"
            endColor="#9c12d6"
            foreColor={{ "0%": "#6a00d4", "100%": "#9c12d6" }}
            renderCenterView={
              <View
                style={{ width: 100, height: 100, backgroundColor: "gray" }}
              ></View>
            }
          />

## Bug 行为

needMinCircle={true} 无效
renderCenterView 无效

## 期望行为

圆环进度条两端都包含圆形点位
圆环中间部分出现灰色View

## 期望发布日期

期望 bug 解决后发布的正式版本号或日期

## 附件

![IMG_2876](https://user-images.githubusercontent.com/10582533/108580558-efaec980-7366-11eb-94af-15a9a6d44f3e.png)
![IMG_2877](https://user-images.githubusercontent.com/10582533/108580561-f4737d80-7366-11eb-94e7-432d6f40e2f2.png)

**Comment by ZengBeauty** [comment]
反馈问题图片未正常展示，故无法排查。
renderCenterView 可采用定位方法正常展示
