### ISSUE TITLE
TYSectionList组件的ts类型声明问题

### ISSUE THREAD

**Issue by Oliverzzq** [tuya/tuya-panel-kit#50]
## 组件

组件名称：TYSectionList

## 版本

- 组件版本：4.3.3
- react 版本：16.8.3
- react-native 版本：0.59.10

## 概述

Bug 问题概述
TYSectionList的renderItem属性报错标红

## Bug 行为

Bug 的表现行为

## 期望行为

组件的正确行为

## 期望发布日期

期望 bug 解决后发布的正式版本号或日期

## 附件

附上图片或日志
![企业微信截图_dd0135a9-6235-4c42-8247-561155b6fc38](https://user-images.githubusercontent.com/18691844/110086072-e1cc6000-7dcc-11eb-9b07-7ecffa03dc9f.png)

**Comment by youngjuning** [comment]
@Oliverzzq 您好，麻烦附上报错信息和 @types/tuya-panel-kit 版本？

**Comment by Oliverzzq** [comment]
@types/tuya-panel-kit 版本: 
![企业微信截图_20129d4a-06fb-4d3f-a2f5-895fbca901be](https://user-images.githubusercontent.com/18691844/110089405-0cb8b300-7dd1-11eb-878f-df890ff8515d.png)
4.0.1

**Comment by ShinyLeee** [comment]
LogItem 是怎么定义的？ @Oliverzzq 可以尝试下以下方式

```tsx
    <TYSectionList<LogItem> {...props} />
```
