### ISSUE TITLE
SwitchButton Size属性不传报错

### ISSUE THREAD

**Issue by yefengxing** [tuya/tuya-panel-kit#62]
## 组件

组件名称 SwitchButton

## 版本

- 组件版本： 4.5.2
- react 版本：16.8.3
- react-native 版本：0.59.10

## 概述

SwitchButton 组件没传入size值，页面崩溃

## 重现步骤

1. 页面引入SwitchButton组件
2. 进入页面
3. 页面崩溃

## Bug 行为

页面崩溃

## 期望行为

正常展示

## 期望发布日期

4.5.3

## 附件

![Simulator Screen Shot - iPhone Xs Max - 2021-04-16 at 10 04 10](https://user-images.githubusercontent.com/23026338/114961759-09b6e500-9e9c-11eb-97f1-a81532878d34.png)

**Comment by ZengBeauty** [comment]
@yefengxing 经过验证，不会出现崩溃现象，demo 可参考 https://github.com/tuya/tuya-panel-kit/blob/master/example/src/scenes/Switch/index.js
