### ISSUE TITLE
popup.list 组件 title 分割线不显示

### ISSUE THREAD

**Issue by yefengxing** [tuya/tuya-panel-kit#71]
## 组件

popup.list

## 版本

- 组件版本：4.5.4
- react 版本：16.8.3
- react-native 版本：0.59.10

## 概述

安卓机型 popup.list 组件 在dark模式下，title分割线不显示

## Bug 行为

展示异常

## 期望行为

分割线展示完全

## 期望发布日期

2021.05.31

**Comment by ZengBeauty** [comment]
@yefengxing 提供一下问题图片

**Comment by ZengBeauty** [comment]
![image](https://user-images.githubusercontent.com/34674396/119782272-8ce94300-befe-11eb-8d42-1f640384cbcb.png)
