### ISSUE TITLE
使用组件库报错

### ISSUE THREAD

**Issue by theecn** [tuya/tuya-panel-kit#73]
## 组件

组件名称

## 版本

- 组件版本：4.5.4
- react 版本：
- react-native 版本：

## 概述

Bug 问题概述

## 重现步骤

1. expo init myApp  yarn add myApp
2. yarn start
3、执行报错

## Bug 行为

Bug 的表现行为

## 期望行为

组件的正确行为

## 期望发布日期

期望 bug 解决后发布的正式版本号或日期

## 附件

附上图片或日志
![image](https://user-images.githubusercontent.com/22100544/120066114-86e29600-c0a7-11eb-83d2-00a1dbaccce0.png)

package.json
![image](https://user-images.githubusercontent.com/22100544/120066127-9b269300-c0a7-11eb-92b8-57c4f5e85d96.png)

**Comment by ShinyLeee** [comment]
@theecn react-native 版本要求为 0.59.10，具体可参见 [package.json -> peerDependency](https://github.com/tuya/tuya-panel-kit/blob/master/package.json#L124)

**Comment by ShinyLeee** [comment]
也可参考 [tuya-panel-demo](https://github.com/tuya/tuya-panel-demo)

**Comment by theecn** [comment]
有提供panel-kit初始化项目的脚手架吗

**Comment by ShinyLeee** [comment]
可参考下 [面板 SDK - 快速入门](https://developer.tuya.com/cn/docs/iot/quick-start?id=K9mfe9upokqq6)

直接初始化项目可参考 [面板 SDK - 快速入门 - 初始化工程](https://developer.tuya.com/cn/docs/iot/initialization-project?id=Kade8if4onqzb#title-3-%E7%AC%AC%E4%BA%8C%E6%AD%A5%EF%BC%9A%E5%88%9D%E5%A7%8B%E5%8C%96%E6%A8%A1%E6%9D%BF%E5%B7%A5%E7%A8%8B)

**Comment by theecn** [comment]
RN，目前用panel-kit这个然后搭上涂鸦的appSDK，运行会有问题。 app开发的sdk 是不再更新了吗？还是你们内部有自己维护一套，不对外公布的？
