### ISSUE TITLE
疑似 DatePicker 组件展示异常

### ISSUE THREAD

**Issue by springjskskjaj** [tuya/tuya-panel-kit#85]
## 组件

DatePicker

## 版本

- 组件版本："tuya-panel-kit": "^4.4.1"
- react 版本：16.8.3
- react-native 版本：5.28

## 概述

在 涂鸦智能 中出现此组件显示异常
SDK Version:3.29.0
但是在OEM App 中却显示正常
SDK Version:3.21.0

## 异常代码

<DatePicker
                            style={{paddingLeft: width * 0.3, paddingRight: width * 0.3, height: height * 0.31}}
                            defaultDate={new Date()}
                            onValueChange={(value, index) => {
                                //console.log(index+value)
                                if (index === 0) {
                                    this.setState({hour2: value})
                                } else if (index === 1) {
                                    this.setState({minute2: value})
                                }
                            }}
                            mode="time"
                        />

## Bug 行为

显示异常，如下图

## 期望行为

正确显示

## 附件
![WPS图片-修改尺寸](https://user-images.githubusercontent.com/61907228/124567163-53e5ac00-de76-11eb-91bf-e342bce92304.jpg)

**Comment by ZengBeauty** [comment]
经过验证，该组件正常展示，暂时关闭该问题
