### ISSUE TITLE
Popup、Dialog、Modal等组件在指定Pad上不能覆盖全屏

### ISSUE THREAD

**Issue by xiaozuanf** [tuya/tuya-panel-kit#86]
## 组件

Popup、Dialog、Modal

## 版本

- 组件版本：3.1、3.0、3.2多个版本
- Pad编号：00480
- Pad型号：Lenovo TB-J706F

## 概述

点击按钮显示Popup、Dialog、Modal等弹框，遮罩未能覆盖全屏

## Bug 行为

遮罩未能覆盖全屏

## 期望行为

遮罩能覆盖全屏

## 期望发布日期

2021.7.30

## 附件

![241625649021_ pic](https://user-images.githubusercontent.com/23622598/124903050-246da580-e016-11eb-88b1-6992b3a3ae18.jpg)

**Comment by ZengBeauty** [comment]
App 3.31 已经完全修复
