### ISSUE TITLE
希望battery组件新增充电中的状态， 以及可以配置水平展示

### ISSUE THREAD

**Issue by baohuse** [tuya/tuya-panel-kit#99]
## 组件
battery
## 概述

希望battery组件新增充电中的状态， 以及可以配置水平展示

## 主要功能点

1. 希望battery组件新增充电中的状态
2. 配置水平展示

## 附件
![企业微信截图_d555efd7-15b1-4a25-ae16-f80b2522c3b1](https://user-images.githubusercontent.com/23302306/127973759-0113357a-aded-4b39-9443-3d26166b9557.png)

**Comment by youngjuning** [comment]
水平旋转就好，就是这个设计稿和组件里的还是有差距的，建议自己实现。
